site_name: HoloAPAC Offkai!
site_url: https://legal.holoapac.live
theme:
  name: material
  logo: assets/holoapac_logo.png
  favicon: assets/holoapac_logo.png
extra:
  social:
    - icon: fontawesome/brands/discord
      name: HoloAPAC Offkai Server!
      link: https://discord.gg/holoapac
    - icon: fontawesome/brands/twitter
      name: HoloAPAC Offkai Twitter
      link: https://twitter.com/HoloAPACOffkai
    - icon: fontawesome/brands/bluesky
      name: HoloAPAC Offkai Bluesky
      link: https://bsky.app/profile/holoapac.live
    - icon: fontawesome/brands/github
      name: HoloAPAC Offkai GitHub
      link: https://github.com/HoloAPAC
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy; 2024-2025 HoloAPAC Offkai